### ISSUE TITLE
Assertion error when loading Kilosort2 output on Phy

### ISSUE THREAD

**Issue by julieelie** [MouseLand/Kilosort2#138]
Hello,
I'm randomly getting issues when loading output data from kilosort2 to Phy, and I can't figure out what's the problem. Could anyone point me to what could cause the error I'm pasting below?
It looks like the output of Kilosort2 is not what phy is expecting in terms of number of clusters?
I'm trying to spike sort long recordings from 4 tetrodes and I'm attaching [here](https://drive.google.com/drive/folders/1LnqNvIuV11ZxoJQo9Yw7iCVB5-QLzgI4) the npy and tsv files that give me the error when loading.
Thank you for your help!
Julie

Here is the error:

Traceback (most recent call last): File "/Users/elie/anaconda3/envs/phy2/bin/phy", line 8, in <module> sys.exit(phycli()) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func return f(get_current_context(), *args, **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/__init__.py", line 156, in cli_template_gui template_gui(params_path, **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/template/gui.py", line 195, in template_gui controller = TemplateController(**get_template_params(params_path), **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/base.py", line 438, in __init__ super(TemplateMixin, self).__init__(*args, **kwargs) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/base.py", line 854, in __init__ self._set_supervisor() File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/template/gui.py", line 95, in _set_supervisor super(TemplateController, self)._set_supervisor() File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/apps/base.py", line 952, in _set_supervisor context=self.context, File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/cluster/supervisor.py", line 661, in __init__ spike_clusters, spikes_per_cluster=spc, new_cluster_id=new_cluster_id) File "/Users/elie/anaconda3/envs/phy2/lib/python3.7/site-packages/phy/cluster/clustering.py", line 157, in __init__ assert np.all(self._spike_clusters < self._new_cluster_id) AssertionError

**Comment by marius10p** [comment]
I think this is a Phy error, @rossant ? I haven't seen errors before where the output of Kilosort is not recognized by Phy. Anything weird or special about the number of detected templates? Post your full command line output please.

**Comment by rossant** [comment]
Is it still happening after you delete the `.phy` subfolder within the data directory?

**Comment by julieelie** [comment]
Hello @marius10p and @rossant,
Indeed removing that hidden folder .phy fixed the problem. It would be nice if the existence of that hidden folder was documented somewhere. Although now the error is searchable on github thanks to that chain ;-)
Thanks!
