### ISSUE TITLE
Out-of-bounds error in phy

### ISSUE THREAD

**Issue by ZeitgeberH** [MouseLand/Kilosort2#69]
Hi,
Kilosort2 output normal npy files. But when i load them in phy, it display the list of clusters but not the wave forms. Console reported errors:
"20:20:45 [E] cli:39               An error has occurred (AssertionError): 
20:20:46 [E] cli:39               An error has occurred (IndexError): index 1390009 is out of bounds for axis 1 with size 1383832" 

in the .phy log, it says:  
"2019-05-24 20:20:46 [D] gui_component:393    Select clusters: 2.
2019-05-24 20:20:46 [E] cli:39               An error has occurred (IndexError): index 1390009 is out of bounds for axis 1 with size 1383832
2019-05-24 20:20:46 [D] cli:42               Traceback (most recent call last):
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/gui/widgets.py", line 196, in _emit_from_js
    self.emit(text_type(name), json.loads(text_type(arg_json)))
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/gui/widgets.py", line 115, in emit
    return self._event.emit(*args, **kwargs)
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/utils/event.py", line 121, in emit
    res.append(callback(*args, **kwargs))
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/cluster/manual/gui_component.py", line 334, in on_select
    self._emit_select(cluster_ids)
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/cluster/manual/gui_component.py", line 395, in _emit_select
    self.gui.emit('select', cluster_ids)
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/gui/gui.py", line 228, in emit
    return self._event.emit(*args, **kwargs)
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/utils/event.py", line 121, in emit
    res.append(callback(*args, **kwargs))
  File "/home/mily99/conda/envs/phy/lib/python3.5/site-packages/phy/cluster/manual/views.py", line 1220, in on_select
    x = self._get_feature(x_dim[i, j], spike_ids, f)
  File "/home/mil99/conda/envs/phy/lib/python3.5/site-packages/phy/cluster/manual/views.py", line 1056, in _get_feature
    return -1. + (2. / self.duration) * self.spike_times[spike_ids]
IndexError: index 1390009 is out of bounds for axis 1 with size 1383832"

**Comment by marius10p** [comment]
It's likely that many other things did not work out correctly. Have you set up Kilosort2 using the Matlab GUI to make sure it is configured correctly?

Can you see templates in Phy by pressing 'w'? Did you see reasonable looking waveforms in Matlab during the optimization? Did it find a reasonable number of spikes?

**Comment by marius10p** [comment]
This issue has become inactive. Closing.
